name: fluttercook
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  cupertino_icons: ^1.0.8
  retrofit: ^4.0.0
  dio: ^5.3.3
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.2



flutter:
  uses-material-design: true
